@startuml
'https://plantuml.com/class-diagram


class Outer {
  Inner inner
  class Inner {
    String data
  }
}

class OuterWithAnonymous {
  Inner anonymous
  class <T> {
    T data
  }
 }
@enduml



